version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
        # https://docs.docker.com/compose/compose-file/#ports
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/html:/var/www/html

